# Generated by Django 3.2.16 on 2023-06-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230612_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
